### ISSUE TITLE
Status line?

### ISSUE THREAD

**Issue by henrikruscon** [henrikdahl/hyperterm-base16-ocean-saturated#3]
Would anyone like a status line? It would basically be a footer holding information such as git status.

I'm thinking the more I add, the more this theme needs options. Right now it's forcing everything upon the user, mainly cuz I made it for myself initially. ✌️

**Comment by henrikruscon** [comment]
Local test of the status line. Just shows the git branch for now. Like it? Should I upload it into the theme? Suggestions on what more to put there? 👋

<img src="https://cloud.githubusercontent.com/assets/1430576/18245740/403bc164-7367-11e6-93dc-5a9b37b70174.png" height="379" alt="">

**Comment by rbartoli** [comment]
I think it looks great, however I see all the useful info already on the pure theme for zsh.

Current branch is already a duplicate, and I was going to suggest all things that are already visible in the theme like dirty working directory / unpulled unpushed / command execution time but probably they don't make much sense as duplicates.

Maybe some properties that apply to the current instance instead of the current folder, like:
- node version
- online status

What were you thinking of adding?

**Comment by henrikruscon** [comment]
Thanks for the feedback! I agree that the most useful information is already provided by zsh.

I was thinking there would be some cases where it's not always visible and useful to have duplicates, while it also enables actions.

Online status is a great suggestion, I'm gonna look into how to implement it.

Tried adding cwd where clicking on it takes you to the directory on finder.

What do you think? 👋

<img src="https://cloud.githubusercontent.com/assets/1430576/18258211/af4c5bbc-73d1-11e6-9463-c85e3ff33abe.png" height="400" alt="">

**Comment by henrikruscon** [comment]
Just pushed status line to the theme. Feel free to try it.

Status line is most likely here to stay but the content is very much open to change. It's also a possibility to fork Pure and remove its git features once the status line one is fully featured itself
